# Generated by Django 4.1.7 on 2023-03-06 13:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_instapost_url'),
        ('about', '0003_alter_chairman_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('photo', models.ImageField(upload_to='event/%Y/%m/%d/', verbose_name='Photo')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('ips', models.GenericIPAddressField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('address_en', models.CharField(max_length=150, null=True, verbose_name='Address')),
                ('address_uz', models.CharField(max_length=150, null=True, verbose_name='Address')),
                ('address_ru', models.CharField(max_length=150, null=True, verbose_name='Address')),
                ('salary', models.CharField(max_length=30, verbose_name='Salary')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('work_volume', models.CharField(max_length=30, verbose_name='Work wolume')),
                ('work_volume_en', models.CharField(max_length=30, null=True, verbose_name='Work wolume')),
                ('work_volume_uz', models.CharField(max_length=30, null=True, verbose_name='Work wolume')),
                ('work_volume_ru', models.CharField(max_length=30, null=True, verbose_name='Work wolume')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chairman',
            name='bio_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='bio_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='bio_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='first_name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='first_name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='first_name_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='last_name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='last_name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='last_name_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='position_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='position_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='position_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='task_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Task'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='task_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Task'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='task_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Task'),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('file', models.FileField(upload_to='resume/%Y/%m/%d/', verbose_name='File')),
                ('email', models.EmailField(max_length=75, verbose_name='Email')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_volunteers', to='about.vacancy', verbose_name='Vacancy')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
        ),
        migrations.CreateModel(
            name='Resme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('full_name_en', models.CharField(max_length=100, null=True, verbose_name='Full name')),
                ('full_name_uz', models.CharField(max_length=100, null=True, verbose_name='Full name')),
                ('full_name_ru', models.CharField(max_length=100, null=True, verbose_name='Full name')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('file', models.FileField(upload_to='resume/%Y/%m/%d/', verbose_name='File')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_voluntrs', to='about.vacancy', verbose_name='Vacancy')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('first_name_en', models.CharField(max_length=30, null=True, verbose_name='First name')),
                ('first_name_uz', models.CharField(max_length=30, null=True, verbose_name='First name')),
                ('first_name_ru', models.CharField(max_length=30, null=True, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('last_name_en', models.CharField(max_length=30, null=True, verbose_name='Last name')),
                ('last_name_uz', models.CharField(max_length=30, null=True, verbose_name='Last name')),
                ('last_name_ru', models.CharField(max_length=30, null=True, verbose_name='Last name')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('position_en', models.CharField(max_length=100, null=True, verbose_name='Position')),
                ('position_uz', models.CharField(max_length=100, null=True, verbose_name='Position')),
                ('position_ru', models.CharField(max_length=100, null=True, verbose_name='Position')),
                ('photo', models.ImageField(upload_to='user', verbose_name='Photo')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Bio')),
                ('bio_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Bio')),
                ('bio_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Bio')),
                ('bio_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Bio')),
                ('task', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Task')),
                ('task_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Task')),
                ('task_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Task')),
                ('task_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Task')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_agents', to='common.countrybase', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Chairman',
                'verbose_name_plural': 'Chairmen',
            },
        ),
    ]
