# Generated by Django 4.1.7 on 2023-03-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_vacancy_chairman_bio_en_chairman_bio_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': "Volunteer's Resume", 'verbose_name_plural': "Volunteer's Resumes"},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
    ]
