# Generated by Django 4.1.7 on 2023-03-07 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_instapost_url'),
        ('service', '0003_author_benefitsofvolunteering_careerbridge_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forvolunteer',
            options={'verbose_name': 'For Volunteer Content', 'verbose_name_plural': 'For Volunteer Contents'},
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('birthday', models.DateField(verbose_name='Region')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('activity', models.CharField(max_length=50, verbose_name='Activity')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('time', models.CharField(choices=[('Да, смогу', 'Yes'), ('Нет, только на половину дня', 'No'), ('Другое', 'Other')], default='Да, смогу', max_length=30)),
                ('continues', models.CharField(choices=[('Полный день', 'Full Day'), ('Неполный рабочий день', 'Part Time'), ('Нет, только на летний период', 'Only Summer'), ('Другое', 'Other')], default='Неполный рабочий день', max_length=30)),
                ('university', models.CharField(max_length=150, verbose_name='Education')),
                ('faculty', models.CharField(max_length=150, verbose_name='Faculty')),
                ('enter_year', models.IntegerField(default=2020, verbose_name='Enter year')),
                ('end_year', models.IntegerField(default=2020, verbose_name='End year')),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='GPA')),
                ('experience', models.TextField(verbose_name='Experience')),
                ('knowledge', models.TextField(verbose_name='Knowledge')),
                ('resume', models.FileField(upload_to='intern_resume', verbose_name='resume')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='region_interns', to='common.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Intership in Uzbekistan',
                'verbose_name_plural': 'Interships in Uzbekistan',
            },
        ),
    ]
