# Generated by Django 4.1.7 on 2023-03-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_instapost_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='instapost',
            name='url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
