# Generated by Django 4.1.7 on 2023-03-04 06:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='task',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Task'),
        ),
    ]
