# Generated by Django 4.1.7 on 2023-03-06 13:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_teammember_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='about_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='About project'),
        ),
        migrations.AddField(
            model_name='project',
            name='about_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='About project'),
        ),
        migrations.AddField(
            model_name='project',
            name='about_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='About project'),
        ),
        migrations.AddField(
            model_name='project',
            name='all_document_text_en',
            field=models.TextField(null=True, verbose_name='All document text'),
        ),
        migrations.AddField(
            model_name='project',
            name='all_document_text_ru',
            field=models.TextField(null=True, verbose_name='All document text'),
        ),
        migrations.AddField(
            model_name='project',
            name='all_document_text_uz',
            field=models.TextField(null=True, verbose_name='All document text'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='task',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='task',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='task',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='task',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='task',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='task',
            name='title_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='first_name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='first_name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='first_name_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='last_name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='last_name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='last_name_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='task_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Task'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='task_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Task'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='task_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Task'),
        ),
    ]
